---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "tush-app.labels" . | nindent 4 }}
spec:
  selector:
     app: {{ .Values.app_name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "tush-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      serviceAccountName: secrets-service-account
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "eks-cluster-secrets"
      containers:
        - name: {{ .Values.app_name }}
          image: {{ $image := print .Values.container.image .Values.TARGET_SHA }}{{ $image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            {{- range .Values.env }}
            - name: {{ regexSplit "=" . -1 | first }}
              value: {{ regexSplit "=" . -1 | last }}
            {{- end }}