---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "tush-app.labels" . | nindent 4 }}
spec:
  selector:
     app: {{ .Values.app_name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "tush-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      serviceAccountName: secrets-service-account
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "eks-cluster-secrets"
      containers:
        - name: {{ .Values.app_name }}
          image: {{ $image := print .Values.container.image .Values.TARGET_SHA }}{{ $image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SENTRY_KEY
              valueFrom:
                secretKeyRef:
                  name: tush-app-env-vars
                  key: tush_sentry_key
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tush-app-env-vars
                  key: datadog_api_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: tush-app-env-vars
                  key: tush_aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tush-app-env-vars
                  key: tush_aws_secret_key
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: eventstream-kafka-client-credentials
                  key: eventstream_kafka_brokers
            - name: EVENTSTREAM_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: eventstream-kafka-client-credentials
                  key: registry_access_key
            - name: EVENTSTREAM_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: eventstream-kafka-client-credentials
                  key: registry_secret_key
            - name: EVENTSTREAM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eventstream-kafka-client-credentials
                  key: kafka_scram_username
            - name: EVENTSTREAM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventstream-kafka-client-credentials
                  key: kafka_scram_password
