apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app_name }}-post-install-job
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "tush-app.chart" . }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Values.app_name }}-post-install-job
      labels:
        helm.sh/chart: {{ include "tush-app.chart" . }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.app_name }}-post-install-job
        image: 788737964674.dkr.ecr.us-west-2.amazonaws.com/gbg/httpie
        command: ["http","https://api.github.com/repos/GoodBuyGear/webapp/deployments/{{ .Values.DEPLOYMENT_ID }}/statuses Authorization:'Basic {{ .Values.GITHUB_TOKEN }}' state=success --follow --debug --verify=no --json"]

