app_name: tush-app
namespace: default
replicas: 1
container:
  image: "788737964674.dkr.ecr.us-west-2.amazonaws.com/gbg/tush-app:"
env:
  - DATADOG_PORT='8126'
  - NODE_ENV='development'
  - NPM_CONFIG_PRODUCTION="false"
  - NPM_USE_PRODUCTION="false"
  - NPM_USE_REMOTE="true"
  - server="3"
  - SERVER_BASE_URL="https://api.gbgstaging.com"
  - DIRECT_SERVER_BASE_URL="https://api.gbgstaging.com"
  - CLIENT_SIDE_URL="https://api.gbgstaging.com"
  - CLUSTER_NAME="GBG-STAGING"